### ISSUE TITLE
[p2p Code Review] Suggestions for improvement

### ISSUE THREAD

**Issue by gvgesanto2** [fibini/Portfolio-project#15]
## Hi @fibini  👋,

Very good implementation of the fourth Figma template, congrats!

## To Highlight 💯 
✔️ Very good UI design (it resembles the fourth Figma template a lot)
✔️ Good use of Flexbox
✔️ Good use of CSS Grid in different parts of the code
✔️ Good use of animations and transitions

## Suggestions

- Try to use relative length units (e.g. rem, em, vw, vh, %) instead of absolute length units (e.g. px). This will make working on your webpage responsiveness an easier job for you.
- Try to avoid using fixed height and width lengths for containers. Even though this is not an unbreakable rule, it can make your life easier in making your webpage responsive.
- For readability and code cleanliness purposes, try to avoid leaving commented-out code blocks in your codebase.
- You have this minor design issue in your project popup window: 
  ![popup-scroll](https://user-images.githubusercontent.com/64566209/169340441-e29fa996-515d-4326-a107-426e5d9a4018.png)

    **Depending on the user's device screen height, it's impossible to see the whole page content.** To solve this problem you could do this:
   - In your ``popup-box`` class, add the property ``overflow-y: scroll;``
   - In your ``popup-window`` class, delete the property ``position: fixed;`` on both the mobile and desktop (media queries) selectors, and add the property ``margin: 0 auto`` to center the popup-window inside the popup-box.
 
   **So your code would be like this:**
   ```css
    .popup-box {
       width: 100%;
      height: 100%;
      position: fixed;
      top: 0;
      left: 0;
      opacity: 1;
      background-color: rgba(255, 255, 255, 0.16);
      overflow-y: scroll; /* ADD THIS PROPERTY */
    }
   .popup-window {
     display: flex;
     flex-direction: column;
     justify-content: center;
     color: white;
     background-color: #191765;
     box-shadow: 0 48px 48px rgb(37 47 137 / 8%);
     border: 1px solid white;
     width: 80%;
     margin: 0 auto; /* ADD THIS PROPERTY */
    }
   @media only screen and (min-width: 768px) {
   .popup-window {
      /* In the media queries selectors, you just need to add the properties you want to override or append */
      width: 60%;
      height: auto;
    }
  }
   ```
- For accessibility purposes, your form inputs should have labels. To do this without changing your design you have two options:
  - Implement the labels in your HTML and hide them using CSS (which I personally don't like)
  - **The best one**: add an ``aria-label`` attribute to the form inputs and textarea. This will provide an invisible label for the input and textarea objects that can be read by assistive technology (e.g. screen readers) without changing your portfolio design. So, in this case, for example, your inputs would look like this: 
  ```html
         <input
            type="text"
            id="name"
            name="user"
            maxlength="30"
            placeholder="Text input"
            required
            aria-label="enter your name"
          />
   ```
   We can see this technique being used in the login form input of Google (which doesn't have a ``label`` tag associated with it, but an ``aria-label`` attribute instead), for example: 
   ![google-login-form](https://user-images.githubusercontent.com/64566209/166605641-856a2920-ef5b-44e1-81fd-401aa78c55d9.png)
